name: Linting- Markdown,Shell

on:
  push:
  workflow_dispatch:

jobs:
  markdown-linting:
    name: Markdown lint
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: markdownlint-cli
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          config: ".markdownlint.json"
          globs:  |
            **/*.md
            !**/.github/**/*.md


  markdown-check-links:
    name: Markdown - checking links
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ".markdownlint.json"

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
