name: Python CI

on: [push, pull_request, workflow_dispatch]

jobs:
  python-ci:

    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - uses: psf/black@stable
      with:
        options: "--check --verbose --diff --color"
        src: "./src"
        version: "~= 24.10"
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==2.16.4
    - name: Lint with Pylint
      run: |
        # Stop the build if there are Python linting errors
        pylint --rcfile .pylintrc src
